# Generated by Django 2.0 on 2017-12-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
	migrations.RunSQL(
		('CREATE FULLTEXT INDEX entry_fulltext_index ON blog_entry (title,body)',),
		('DROP INDEX entry_fulltext_index on blog_entry',)
	)
    ]
