# Generated by Django 2.0 on 2017-12-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171216_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=145, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(max_length=145, unique=True),
        ),
    ]
