# Generated by Django 2.0 on 2017-12-21 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_id', models.CharField(max_length=32)),
                ('address_type', models.CharField(choices=[('SHP', 'SHIP_TO'), ('BILL', 'BILLING')], max_length=6)),
                ('address_1', models.CharField(max_length=32)),
                ('address_2', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('zipcode', models.CharField(max_length=32)),
                ('primary', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_group_id', models.CharField(max_length=32)),
                ('category_group_name', models.CharField(max_length=32)),
                ('transaction_type', models.CharField(choices=[('SHIPMENT', 'SHIPMENT'), ('HOMESALE', 'HOMESALE'), ('SOMETHING', 'Something else')], max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.CharField(max_length=32)),
                ('primary_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('contact_type', models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=32)),
                ('customer_status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('HOLD', 'HOLD')], default='OPEN', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=32)),
                ('order_status', models.CharField(choices=[('OPEN', 'OPEN'), ('HOLD', 'HOLD'), ('CLOSED', 'CLOSED')], max_length=32)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2017, 12, 21, 16, 36, 43, 947078))),
                ('order_fulfill_date', models.DateTimeField(verbose_name=datetime.datetime(2017, 12, 21, 16, 36, 43, 947100))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=64)),
                ('product_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('sell_for_amount', models.FloatField(max_length=10)),
                ('est_tax_amount', models.FloatField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRateByZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=12)),
                ('tax_region_name', models.CharField(max_length=120)),
                ('state_rate', models.FloatField(max_length=10)),
                ('est_combined_rate', models.FloatField(max_length=10)),
                ('est_county_rate', models.FloatField(max_length=10)),
                ('est_city_rate', models.FloatField(max_length=10)),
                ('est_special_rate', models.FloatField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer'),
        ),
    ]
