# Generated by Django 2.0 on 2017-12-22 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 13, 39, 36, 445216)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_fulfill_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 12, 22, 13, 39, 36, 445238)),
        ),
    ]
